compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

packageExtensions:
  "@apollo/experimental-nextjs-app-support@*":
    peerDependencies:
      graphql: "*"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-tools/apollo-engine-loader": "*"
  "@rushstack/eslint-patch@*":
    peerDependencies:
      "@eslint/eslintrc": "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react@*":
    peerDependencies:
      prop-types: "*"
      scheduler: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-next@*:
    peerDependencies:
      "@eslint/eslintrc": "*"
      next: "*"
  next@*:
    dependencies:
      sharp: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  rollup@*:
    peerDependencies:
      source-map-support: "*"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.0.2.cjs
